### ISSUE TITLE
Error after upload

### ISSUE THREAD

**Issue by tjluoma** [filon2008/OvercastUploader#1]
the script _seemed_ to work (although it did output a bunch of HTML (which I think is the actual content of my <https://overcast.fm/uploads> page, but after uploading, it ends with this message:

```
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Extra input fields: 
success_action_redirect</Message><RequestId>82CC335DDF3E4024</RequestId>
<HostId>muC4lBS+USe5WsmQIDU7JNj9CuRKvuqTsk7mYhrUo0eL8C1CoovF6//lGhsfLp25EaDrJStDD8c=</HostId></Error>%
```

and the file is _not_ successfully uploaded.

Unfortunately I have no idea what to do to fix it.

**Comment by GektorGrom** [comment]
@tjluoma I've added changes to help you successfully upload file. check PR #2
